spring.application.name=schoolmanager
server.port=8080

# ================= DATABASE POSTGRESQL (RENDER) =================
spring.datasource.url=jdbc:postgresql://dpg-d5uvfsfpm1nc73c6lkng-a.oregon-postgres.render.com:5432/schoolmanager_kbge
spring.datasource.username=schoolmanager
spring.datasource.password=U1PGDaikyfPtl2xUhCPk16lSmWDTCNTS

spring.datasource.driver-class-name=org.postgresql.Driver

# ================= JPA / HIBERNATE =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ================= THYMELEAF =================
spring.thymeleaf.cache=false
