spring.application.name=schoolmanager
server.port=8080

# DATABASE
spring.datasource.url=jdbc:postgresql://dpg-d7tkktkm0tmc73cs00n0-a.singapore-postgres.render.com:5432/schoolmanager_7tpt?sslmode=require
spring.datasource.username=schoolmanager
spring.datasource.password=hZ4V85UWosyk67Px9YWpFaHBDTqkrRlu
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# THYMELEAF
spring.thymeleaf.cache=false
