spring.application.name=schoolmanager
server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-abc123.render.com:5432/schoolmanager
spring.datasource.username=schoolmanager
spring.datasource.password=Mj8AxGoSyqc6nSvSIlJYAg3rt1GZxifo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false
